name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@main
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # plugins
          user: alikzalikz
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Tehran
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_ignored: automator, verified, explorer, infographile
          plugin_languages: yes
          plugin_languages_ignored: markdown, html, lua, other
          plugin_languages_details: percentage
          plugin_languages_other: yes
          plugin_languages_threshold: 5%
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
